/*:
 * @plugindesc Система огорода (Updated 2023)
 * @author Pheonix KageDesu
 *
 * @help
 * 
 * Файл настроек data\PKD_Farm.json
 * Изображения img\pkd_farm
 * 
 * Инструкцию см.в файле Note.docx
 * 
 * Команды плагина:
 * StartFarming - начать посадку
 * EndFarming - сбор урожая
 * 
 * 
 * ClearFarmingResults - очистить динамические объекты из памяти, не обязательно, служебная команда
 * Эту команду надо выполнять в отдельном событии


 * 
 * 
 */



//@[CODE STANDARD X3]

/* jshint -W097 */
/* jshint -W117 */


var Imported = Imported || {};

var PKD = PKD || {};
PKD.LIBS = PKD.LIBS || {};

PKD.FARM = {};

DataManager._databaseFiles.push({
    name: '$PKD_Farm',
    src: 'PKD_Farm.json'  
});

PKD.FARM.SPRITE = function (filename) {
    return new Sprite(PKD.FARM.IMG(filename));
};

PKD.FARM.IMG = function (filename) {
    return ImageManager.loadBitmap('img/pkd_Farm/', filename, 0, true);
};

//@[ALIAS]
var _Game_Interpreter_pluginCommand_3434 = Game_Interpreter.prototype.pluginCommand;
Game_Interpreter.prototype.pluginCommand = function (command, args) {
    _Game_Interpreter_pluginCommand_3434.call(this, command, args);
    if (command === 'StartFarming') {
        try {

            $gameTemp._currentFarmEvent = this.eventId();
            SceneManager.push(Scene_Farm);

        } catch (e) {
            console.warn(e);
        }
    } else if (command === 'EndFarming') {
        try {
        
            FarmManager.getItemFromSpotData(this.eventId());

        } catch (e) {
            console.warn(e);
        }
    } else if (command === 'ClearFarmingResults') {
        try {

            FarmManager.clearNotUsedDinamics();

        } catch (e) {
            console.warn(e);
        }
    }
};

(function(){
    
    // * Сбор дополнительных параметров из заметок предметов
    //@[ALIAS]
    var _alias_DataManager_extractMetadata = DataManager.extractMetadata;
    DataManager.extractMetadata = function (data) {
        _alias_DataManager_extractMetadata.call(this, data);
        DataManager.registerFarmMeta(data, 'farmItemA');
        DataManager.registerFarmMeta(data, 'farmItemB');
        DataManager.registerFarmMeta(data, 'farmItemC');
        DataManager.registerFarmMeta(data, 'farmItemD');
        if (PKD.Utils.hasMeta('farmResult', data)) {
            var itemId = PKD.Utils.getNumberFromMeta('farmResult', data);
            if(itemId > 0)
                data.farmResult = itemId;
        }
        if (PKD.Utils.hasMeta('farmTime', data)) {
            var time = PKD.Utils.getNumberFromMeta('farmTime', data);
            if (time > 0)
                data.farmTime = time;
        }
        if(data.farmItemA == true) {
            DataManager.registerComplexFarmMeta(data, 'farmImgA');
            DataManager.registerComplexFarmMeta(data, 'farmImgB');
            DataManager.registerComplexFarmMeta(data, 'farmImgC');
            DataManager.registerComplexFarmMeta(data, 'farmImgD');
        }
    };

    //?[NEW]
    DataManager.registerFarmMeta = function(data, meta) {
        if (PKD.Utils.hasMeta(meta, data)) {
            data[meta] = true;
        }
    };

    //?[NEW]
    DataManager.registerComplexFarmMeta = function (data, meta) {
        if (PKD.Utils.hasMeta(meta, data)) {
            var value = PKD.Utils.getValueFromMeta(meta, data);
            if(value.contains(',')) {
                var parts = value.trim().split(",");
                if(parts.length > 1) {
                    var partA = parts[0].trim();
                    var partB = Number(parts[1].trim());
                    data[meta] = [partA, partB];
                }
            } else {
                data[meta] = [Number(value.trim()), null];
            }
        }
    };

    //@[ALIAS]
    var _alias_DataManager_isItem = DataManager.isItem;
    DataManager.isItem = function (item) {
        if(item) {
            if (FarmManager.isDinamycItemId(item.id)) {
                return $gamePlayer.isContainsDynamicItem(item.id);
            }
        }
        return _alias_DataManager_isItem.call(this, item);
    };

})();

// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ KDCore.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//@[MIN VERSION with MV < 1.6.1 SUPPORT]
var KDCore;

KDCore = KDCore || {};

KDCore.Version = '1.11M';

KDCore.LIBS = {};

KDCore.register = function(library) {
  return this.LIBS[library.name] = library;
};

(function() {
  var BitmapSrc, Color, SDK, ___Sprite_alias_Move_KDCORE_ABS, __alias_Bitmap_fillAll;
  //Array Extension
  //------------------------------------------------------------------------------
  Array.prototype.delete = function() {
    var L, a, ax, what;
    what = void 0;
    a = arguments;
    L = a.length;
    ax = void 0;
    while (L && this.length) {
      what = a[--L];
      while ((ax = this.indexOf(what)) !== -1) {
        this.splice(ax, 1);
      }
    }
    return this;
  };
  Array.prototype.include = function(value) {
    return this.indexOf(value) !== -1;
  };
  //?[FOR 1.5.1]
  Array.prototype.includes = function(value) {
    return this.include(value);
  };
  Array.prototype.max = function() {
    return Math.max.apply(null, this);
  };
  Array.prototype.min = function() {
    return Math.min.apply(null, this);
  };
  Array.prototype.sample = function() {
    if (this.length === 0) {
      return [];
    }
    return this[SDK.rand(0, this.length - 1)];
  };
  Array.prototype.first = function() {
    return this[0];
  };
  Array.prototype.last = function() {
    return this[this.length - 1];
  };
  Array.prototype.shuffle = function() {
    var k, n, v;
    n = this.length;
    while (n > 1) {
      n--;
      k = SDK.rand(0, n + 1);
      v = this[k];
      this[k] = this[n];
      this[n] = v;
    }
  };
  Array.prototype.count = function() {
    return this.length;
  };
  //Number Extension
  //------------------------------------------------------------------------------
  Number.prototype.do = function(method) {
    return SDK.times(this, method);
  };
  Number.prototype.clamp = function(min, max) {
    return Math.min(Math.max(this, min), max);
  };
  //Sprite Extension
  //------------------------------------------------------------------------------
  Sprite.prototype.moveToCenter = function(dx, dy) {
    dx = SDK.check(dx, 0);
    dy = SDK.check(dy, 0);
    return this.move(-this.bitmap.width / 2 + dx, -this.bitmap.height / 2 + dy);
  };
  Sprite.prototype.setStaticAnchor = function(floatX, floatY) {
    this.x -= Math.round(this.width * floatX);
    this.y -= Math.round(this.height * floatY);
  };
  Sprite.prototype.moveToParentCenter = function() {
    if (!this.parent) {
      return;
    }
    return this.move(this.parent.width / 2, this.parent.height / 2);
  };
  ___Sprite_alias_Move_KDCORE_ABS = Sprite.prototype.move;
  Sprite.prototype.move = function(x, y) {
    if (x instanceof Array) {
      return ___Sprite_alias_Move_KDCORE_ABS.call(this, x[0], x[1]);
    } else {
      return ___Sprite_alias_Move_KDCORE_ABS.call(this, x, y);
    }
  };
  //Bitmap Extension
  //------------------------------------------------------------------------------
  __alias_Bitmap_fillAll = Bitmap.prototype.fillAll;
  Bitmap.prototype.fillAll = function(color) {
    if (color instanceof KDCore.Color) {
      return this.fillRect(0, 0, this.width, this.height, color.CSS);
    } else {
      return __alias_Bitmap_fillAll.call(this, color);
    }
  };
  Bitmap.prototype.drawIcon = function(x, y, icon, size) {
    var bitmap;
    size = SDK.check(size, 32);
    bitmap = null;
    if (icon instanceof Bitmap) {
      bitmap = icon;
    } else {
      bitmap = BitmapSrc.LoadFromIconIndex(icon).bitmap;
    }
    return this.drawOnMe(bitmap, x, y, size, size);
  };
  Bitmap.prototype.drawOnMe = function(bitmap, x, y, sw, sh) {
    x = SDK.check(x, 0);
    y = SDK.check(y, 0);
    sw = SDK.check(sw, 0);
    sh = SDK.check(sh, 0);
    if (sw <= 0) {
      sw = bitmap.width;
    }
    if (sh <= 0) {
      sh = bitmap.height;
    }
    this.blt(bitmap, 0, 0, bitmap.width, bitmap.height, x, y, sw, sh);
  };
  Bitmap.prototype.drawTextFull = function(text, position) {
    position = SDK.check(position, 'center');
    return this.drawText(text, 0, 0, this.width, this.height, position);
  };
  //SDK
  //------------------------------------------------------------------------------
  SDK = function() {
    throw new Error('This is a static class');
  };
  SDK.rand = function(min, max) {
    return Math.round(Math.random() * (max - min)) + min;
  };
  SDK.setConstantToObject = function(object, constantName, constantValue) {
    object[constantName] = constantValue;
    if (typeof object[constantName] === 'object') {
      Object.freeze(object[constantName]);
    }
    Object.defineProperty(object, constantName, {
      writable: false
    });
  };
  SDK.convertBitmapToBase64Data = function(bitmap) {
    return bitmap._canvas.toDataURL('image/png');
  };
  SDK.times = function(times, method) {
    var i, results;
    i = 0;
    results = [];
    while (i < times) {
      method(i);
      results.push(i++);
    }
    return results;
  };
  SDK.toGlobalCoord = function(layer, coordSymbol) {
    var node, t;
    coordSymbol = SDK.check(coordSymbol, 'x');
    t = layer[coordSymbol];
    node = layer;
    while (node) {
      t -= node[coordSymbol];
      node = node.parent;
    }
    return (t * -1) + layer[coordSymbol];
  };
  SDK.isInt = function(n) {
    return Number(n) === n && n % 1 === 0;
  };
  SDK.isFloat = function(n) {
    return Number(n) === n && n % 1 !== 0;
  };
  SDK.check = function(value, defaultValue) {
    if (defaultValue === void 0 || defaultValue === null) {
      defaultValue = true;
    }
    if (value === void 0 || value === null) {
      return defaultValue;
    } else {
      return value;
    }
  };
  SDK.checkSwitch = function(switchValue) {
    if (switchValue === 'A' || switchValue === 'B' || switchValue === 'C' || switchValue === 'D') {
      return true;
    }
    return false;
  };
  //For compability with PLATFORM
  SDK.setConstant = function(object, name, value) {
    return SDK.setConstantToObject(object, name, value);
  };
  //Color
  //------------------------------------------------------------------------------
  Color = class Color {
    constructor(r1, g1, b1, a1) {
      this.r = r1;
      this.g = g1;
      this.b = b1;
      this.a = a1;
      this.r = SDK.check(this.r, 255);
      this.g = SDK.check(this.g, 255);
      this.b = SDK.check(this.b, 255);
      this.a = SDK.check(this.a, 255);
    }

    getLightestColor(lightLevel) {
      var bf, newColor, p;
      bf = 0.3 * this.R + 0.59 * this.G + 0.11 * this.B;
      p = 0;
      newColor = [0, 0, 0, 0];
      if (bf - lightLevel >= 0) {
        if (bf >= 0) {
          p = Math.abs(bf - lightLevel) / lightLevel;
        }
        newColor = this.ARR.map(function(c) {
          return c - (p * c);
        });
      } else {
        if (bf >= 0) {
          p = (lightLevel - bf) / (255 - bf);
        }
        newColor = this.ARR.map(function(c) {
          return [(255 - c) * p + c, 255].min();
        });
      }
      return new Color(newColor[0], newColor[1], newColor[2], newColor[3]);
    }

    clone() {
      return this.reAlpha(this.a);
    }

    reAlpha(newAlpha) {
      return new Color(this.r, this.g, this.b, newAlpha || 255);
    }

    static AddConstantColor(name, color) {
      color.toHex();
      color.toArray();
      color.toCSS();
      SDK.setConstantToObject(Color, name, color);
    }

    toHex() {
      var b, g, r;
      if (this._colorHex != null) {
        return this._colorHex;
      }
      r = Math.floor(this.r).toString(16).padZero(2);
      g = Math.floor(this.g).toString(16).padZero(2);
      b = Math.floor(this.b).toString(16).padZero(2);
      return this._colorHex = '#' + r + g + b;
    }

    toArray() {
      if (this._colorArray != null) {
        return this._colorArray;
      }
      return this._colorArray = [this.r, this.g, this.b, this.a];
    }

    toCSS() {
      var na, nb, ng, nr;
      if (this._colorCss != null) {
        return this._colorCss;
      }
      nr = Math.round(this.r);
      ng = Math.round(this.g);
      nb = Math.round(this.b);
      na = this.a / 255;
      return this._colorCss = `rgba(${nr},${ng},${nb},${na})`;
    }

    static Random() {
      var a, b, c;
      a = SDK.rand(1, 254);
      b = SDK.rand(1, 254);
      c = SDK.rand(1, 254);
      return new Color(a, b, c, 255);
    }

    static FromHex(hexString) {
      var color, result;
      result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hexString);
      color = null;
      if (result != null) {
        color = {
          r: parseInt(result[1], 16),
          g: parseInt(result[2], 16),
          b: parseInt(result[3], 16)
        };
      }
      if (color != null) {
        return new Color(color.r, color.g, color.b, 255);
      } else {
        return Color.NONE;
      }
    }

  };
  Object.defineProperties(Color.prototype, {
    R: {
      get: function() {
        return this.r;
      },
      configurable: true
    },
    G: {
      get: function() {
        return this.g;
      },
      configurable: true
    },
    B: {
      get: function() {
        return this.b;
      },
      configurable: true
    },
    A: {
      get: function() {
        return this.a;
      },
      configurable: true
    },
    ARR: {
      get: function() {
        return this.toArray();
      },
      configurable: true
    },
    CSS: {
      get: function() {
        return this.toCSS();
      },
      configurable: true
    },
    HEX: {
      get: function() {
        return this.toHex();
      },
      configurable: true
    }
  });
  Color.AddConstantColor('NONE', new Color(0, 0, 0, 0));
  Color.AddConstantColor('BLACK', new Color(0, 0, 0, 255));
  Color.AddConstantColor('WHITE', new Color(255, 255, 255, 255));
  Color.AddConstantColor('RED', new Color(255, 0, 0, 255));
  Color.AddConstantColor('GREEN', new Color(0, 255, 0, 255));
  Color.AddConstantColor('BLUE', new Color(0, 0, 255, 255));
  Color.AddConstantColor('AQUA', new Color(128, 255, 255, 255));
  Color.AddConstantColor('MAGENTA', new Color(128, 0, 128, 255));
  Color.AddConstantColor('YELLOW', new Color(255, 255, 0, 255));
  Color.AddConstantColor('ORANGE', new Color(255, 128, 0, 255));
  BitmapSrc = (function() {
    //BitmapSrc
    //------------------------------------------------------------------------------
    class BitmapSrc {
      constructor() {
        this.bitmap = null;
      }

      static LoadFromIconIndex(iconIndex) {
        var bs, icon_bitmap, iconset, ph, pw, sx, sy;
        bs = new BitmapSrc();
        if (BitmapSrc.CACHE[iconIndex] == null) {
          iconset = ImageManager.loadSystem('IconSet');
          pw = Window_Base._iconWidth;
          ph = Window_Base._iconHeight;
          sx = iconIndex % 16 * pw;
          sy = Math.floor(iconIndex / 16) * ph;
          icon_bitmap = new Bitmap(pw, ph);
          icon_bitmap.addLoadListener(function() {
            icon_bitmap.blt(iconset, sx, sy, pw, ph, 0, 0);
          });
          BitmapSrc.CACHE[iconIndex] = icon_bitmap;
        }
        bs.bitmap = BitmapSrc.CACHE[iconIndex];
        return bs;
      }

      static LoadFromImageFolder(filename) {
        var bs;
        bs = new BitmapSrc();
        bs.bitmap = ImageManager.loadPicture(filename);
        return bs;
      }

      static LoadFromBase64(data, name) {
        var bs;
        bs = new BitmapSrc();
        if (name != null) {
          if (BitmapSrc.CACHE[name] != null) {
            bs.bitmap = BitmapSrc.CACHE[name];
          } else {
            BitmapSrc.CACHE[name] = Bitmap.load(data);
            bs.bitmap = BitmapSrc.CACHE[name];
          }
        } else {
          bs.bitmap = Bitmap.load(data);
        }
        return bs;
      }

      static LoadFromMemory(symbol) {
        var bs;
        bs = new BitmapSrc();
        if (BitmapSrc.CACHE[symbol] != null) {
          bs.bitmap = BitmapSrc.CACHE[symbol];
        } else {
          bs.bitmap = ImageManager.loadEmptyBitmap();
        }
        return bs;
      }

    };

    BitmapSrc.CACHE = {};

    return BitmapSrc;

  }).call(this);
  //EXTENSION TO GLOBAL
  //------------------------------------------------------------------------------
  KDCore.SDK = SDK;
  KDCore.Color = Color;
  KDCore.BitmapSrc = BitmapSrc;
})();

// ■ END KDCore.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Utils.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  _ = {};
  _.hasMeta = function(symbol, obj) {
    return (obj.meta != null) && (obj.meta[symbol] != null);
  };
  _.getValueFromMeta = function(symbol, obj) {
    if (!_.hasMeta(symbol, obj)) {
      return null;
    }
    return obj.meta[symbol];
  };
  _.getNumberFromMeta = function(symbol, obj) {
    var value;
    value = _.getValueFromMeta(symbol, obj);
    if (value != null) {
      return Number(value);
    }
    return 0;
  };
  _.isSceneMap = function() {
    try {
      return SceneManager._scene instanceof Scene_Map;
    } catch (error) {
      return false;
    }
  };
  _.getPositionPointFromJSON = function(jsonSettings) {
    return _.convertPositionPointFromJSON(jsonSettings.position);
  };
  _.convertPositionPointFromJSON = function(position) {
    var e, x, y;
    try {
      x = position[0];
      y = position[1];
      if (!KDCore.SDK.isInt(x)) {
        x = eval(x);
      }
      if (!KDCore.SDK.isInt(y)) {
        y = eval(y);
      }
      return [x, y];
    } catch (error) {
      e = error;
      console.warn(e);
      return [0, 0];
    }
  };
  _.getDataFromJSONById = function(id, data) {
    var e, i, item, j, ref;
    if (data == null) {
      return null;
    }
    try {
      for (i = j = 0, ref = data.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
        item = data[i];
        if (item.id === id) {
          return item;
        }
      }
    } catch (error) {
      e = error;
      console.warn(e);
    }
    return null;
  };
  _.getVar = function(id) {
    return $gameVariables.value(id);
  };
  _.setVar = function(id, value) {
    return $gameVariables.setValue(id, value);
  };
  _.addToVar = function(id, value) {
    var prevVal;
    prevVal = _.getVar(id);
    return _.setVar(id, prevVal + value);
  };
  PKD.Utils = _;
})();

// ■ END Utils.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
var Scene_Farm, Window_FarmItemList, Window_FarmResult, Window_FarmSelectorList;

Scene_Farm = class Scene_Farm extends Scene_Base {
  constructor() {
    super();
  }

};

Window_FarmSelectorList = class Window_FarmSelectorList extends Window_Command {
  constructor(x, y) {
    super(x, y);
    this._afterCreate();
  }

};

Window_FarmResult = class Window_FarmResult extends Window_Base {
  constructor(x, y, w, h) {
    super(x, y, w, h);
    this._afterCreate();
  }

};

Window_FarmItemList = class Window_FarmItemList extends Window_ItemList {
  constructor(x, y, width, height) {
    super(x, y, width, height);
    this._afterCreate();
  }

};


// Generated by CoffeeScript 2.6.1
(function() {})();

//@[DEFINES]
//_ = PKD_Farm.PP

// * paramName, defaultValue
/*_.getLoaderParam = () ->
    try
        PKD_Farm.LoadPluginSettings() unless @_loader?
        return @_loader.getParam(...arguments)
    catch e
        KDCore.warning e
    return null

_.getParamTemplate = () -> @getLoaderParam('name', true)*/


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Farm.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Farm.prototype;
  _.create = function() {
    this._init();
    Scene_Base.prototype.create.call(this);
    Scene_MenuBase.prototype.createBackground.call(this);
    this._createBackgoundImage();
    this.createWindowLayer();
    this._createWindows();
    return this._registerCommands();
  };
  _._init = function() {
    this.S = $PKD_Farm;
    return this._inSecondPhase = false;
  };
  // * Создаёт картинку фона (или ничего, если null)
  _._createBackgoundImage = function() {
    var bakImg;
    if (this.S.BackGroundImg != null) {
      bakImg = PKD.FARM.SPRITE(this.S.BackGroundImg);
      bakImg.move(this.S.BackGroundImgPositon);
      return this.addChild(bakImg);
    }
  };
  _.update = function() {
    Scene_Base.prototype.update.call(this);
    if (this.isExit()) {
      if (this._inSecondPhase === true) {
        return this.popMenu();
      } else {
        return this.popScene();
      }
    }
  };
  _.isExit = function() {
    return Input.isTriggered('cancel') || TouchInput.isCancelled();
  };
})();

// ■ END Scene_Farm.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Window_FarmItemList.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var ALIAS__drawItem, _;
  //@[DEFINES]
  _ = Window_FarmItemList.prototype;
  _._afterCreate = function() {};
  
  // * Показвает окно выбора предмета для компонента
  _.onShow = function() {
    this.showHelpWindow();
    this._helpWindow.open();
    this.activate();
    return this.select(0);
  };
  _.onClose = function() {
    return this._helpWindow.close();
  };
  _.setFarmData = function(fData) {
    this.fData = fData;
  };
  _.isCurrentItemEnabled = function() {
    return true;
  };
  _.maxCols = function() {
    return 1;
  };
  // * Фильтра предметов с учётом выбраного компонента
  _.includes = function(item) {
    if (item == null) {
      return true;
    }
    if (!DataManager.isItem(item)) {
      return false;
    }
    switch (this._category) {
      case 0:
        return item.farmItemA === true;
      case 1:
        return item.farmItemB === true;
      case 2:
        return item.farmItemC === true;
      case 3:
        return item.farmItemD === true;
    }
    return false;
  };
  // * После выбора, установка выбранного предмета в данные грядки
  _.selectItem = function() {
    var item;
    item = this.item();
    switch (this._category) {
      case 0:
        if (item != null) {
          this.fData.itemA = item.id;
        } else {
          this.fData.itemA = 0;
        }
        break;
      case 1:
        if (item != null) {
          this.fData.itemB = item.id;
        } else {
          this.fData.itemB = 0;
        }
        break;
      case 2:
        if (item != null) {
          this.fData.itemC = item.id;
        } else {
          this.fData.itemC = 0;
        }
        break;
      case 3:
        if (item != null) {
          this.fData.itemD = item.id;
        } else {
          this.fData.itemD = 0;
        }
    }
  };
  // * Модифицированный метод отрисовки, добавляет команду Ничего
  //@[ALIAS]
  ALIAS__drawItem = _.drawItem;
  _.drawItem = function(index) {
    var item, rect;
    ALIAS__drawItem.call(this, index);
    item = this._data[index];
    if (item == null) {
      rect = this.itemRect(index);
      rect.width -= this.textPadding();
      return this.drawText('<{Пусто}>', rect.x, rect.y, rect.width, 'center');
    }
  };
})();

// ■ END Window_FarmItemList.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Window_FarmResult.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var _;
  //@[DEFINES]
  _ = Window_FarmResult.prototype;
  // * Получает данные о необходимой грядке, загрузка настроек из JSON
  _._afterCreate = function() {
    this.S = $PKD_Farm;
    this.farmData = FarmManager.getSpotData($gameTemp._currentFarmEvent);
    this._drawHeader();
    return this.refresh();
  };
  // * Рисует заголовок Результат (картинку)
  _._drawHeader = function() {
    this._header = PKD.FARM.SPRITE("Header2");
    this._header.move(this.S.Header2ImgPosition);
    return this.addChild(this._header);
  };
  
  // * Обновить окно (перерисовать)
  _.refresh = function() {
    this.clearAll();
    this.drawYStart = this.S.InfoWindowContentStartY;
    if (this.farmData == null) {
      return;
    }
    if (this.farmData.itemA > 0) {
      this._header.visible = true;
      return this._drawAllInfo();
    } else {
      this._header.visible = false;
      return this._drawNoItemAWarning();
    }
  };
  // * Рисует предупреждение, когда не выбрано достаточное кол-во компонентов
  _._drawNoItemAWarning = function() {
    var startY, textSpr;
    this.drawYStart = this.S.InfoWindowNoItemMsgStartY;
    startY = this.drawYStart;
    this.addSeparateLineShort(this.drawYStart);
    this.drawYStart += 40;
    textSpr = new Sprite(new Bitmap(this.width - 20, 30));
    textSpr.move(10, this.drawYStart);
    textSpr.bitmap.textColor = KDCore.Color.FromHex(this.S.LineColor).CSS;
    textSpr.bitmap.drawTextFull('{Нужно семечко!}', 'center');
    this.add(textSpr);
    this.drawYStart += 80;
    this.addSeparateLineShort(this.drawYStart);
    this.addSeparateLineShortHor(startY, this.drawYStart - startY);
    this.addSeparateLineShortHor2(startY, this.drawYStart - startY);
  };
  // * Эти три метода ниже рисуют линии для предупреждения
  _.addSeparateLineShort = function(y) {
    var b, color, h, line, shadow, w, x;
    x = 44;
    w = this.width - 100;
    h = 3;
    line = new Sprite(new Bitmap(w, h + 2));
    color = KDCore.Color.FromHex(this.S.LineColor).CSS;
    b = line.bitmap;
    b.fillRect(0, 0, w, h, color);
    shadow = KDCore.Color.FromHex("#494453").CSS;
    b.fillRect(0, h, w, 1, shadow);
    line.move(x, y);
    return this.add(line);
  };
  _.addSeparateLineShortHor = function(y, h) {
    var b, color, line, shadow, w, x;
    x = 44;
    w = 3;
    line = new Sprite(new Bitmap(w + 2, h));
    color = KDCore.Color.FromHex(this.S.LineColor).CSS;
    b = line.bitmap;
    b.fillRect(0, 0, w, h, color);
    shadow = KDCore.Color.FromHex("#494453").CSS;
    b.fillRect(w, 3, 1, h, shadow);
    line.move(x, y);
    return this.add(line);
  };
  _.addSeparateLineShortHor2 = function(y, h) {
    var b, color, line, shadow, w, x;
    x = this.width - 100 + 43;
    w = 3;
    line = new Sprite(new Bitmap(w + 2, h + 3));
    color = KDCore.Color.FromHex(this.S.LineColor).CSS;
    b = line.bitmap;
    b.fillRect(0, 0, w, h + 3, color);
    shadow = KDCore.Color.FromHex("#494453").CSS;
    b.fillRect(w, 3, 1, h + 1, shadow);
    line.move(x, y);
    return this.add(line);
  };
  _.add = function(item) {
    return this.mainContent.addChild(item);
  };
  // * Очистка прошлого результата (перед отрисовкой нового)
  _.clearAll = function() {
    this.contents.clear();
    if (this.mainContent != null) {
      this.mainContent.visible = false;
      this.removeChild(this.mainContent);
      this.mainContent.destroy();
    }
    this.mainContent = new Sprite();
    return this.addChild(this.mainContent);
  };
})();

// ■ END Window_FarmResult.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Window_FarmSelectorList.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var ALIAS__initialize, ALIAS__itemRect, _;
  //@[DEFINES]
  _ = Window_FarmSelectorList.prototype;
  _.windowWidth = function() {
    return this.S.SelectorWindowWH[0];
  };
  _.windowHeight = function() {
    return this.S.SelectorWindowWH[1];
  };
  // * Загрузка настроек из JSON, получает данные о текущей грядке
  //@[ALIAS]
  ALIAS__initialize = _.initialize;
  _.initialize = function(x, y) {
    this.farmData = FarmManager.getSpotData($gameTemp._currentFarmEvent);
    this.S = $PKD_Farm;
    return ALIAS__initialize.call(this, x, y);
  };
  // * Отрисовка заголовка и разделительной линии
  _._afterCreate = function() {
    this._header = PKD.FARM.SPRITE("Header");
    this._header.move(this.S.HeaderImgPosition);
    this.addChild(this._header);
    this._footer = PKD.FARM.SPRITE("Footer");
    this._footer.move(this.S.FooterImgPosition);
    return this.addChild(this._footer);
  };
  // * Список кнопок
  _.makeCommandList = function() {
    this.addCommand('{Семечко}', 'partA', true);
    this.addCommand('{Вода}', 'partB', true);
    //@addCommand 'Почва', 'partC', true
    this.addCommand('{Удобрение}', 'partD', true);
    this.addCommand('{Подтвердить}', 'ok', this.isCanUseThis());
    return this.addCommand('{Отмена}', 'cancel', true);
  };
  _.isCanUseThis = function() {
    var ref;
    return (ref = this.farmData) != null ? ref.isCanStartGrown() : void 0;
  };
  // * Начать рост (выполняется после потверждения)
  _.startGrown = function() {
    return this.farmData.startGrown();
  };
  // * Для команд потверждения, добавляем дополнительный отступ
  //@[ALIAS]
  ALIAS__itemRect = _.itemRect;
  _.itemRect = function(index) {
    var rect;
    rect = ALIAS__itemRect.call(this, index);
    rect.y += this.S.HeaderY;
    if (index >= 3) {
      rect.y += this.S.YesCancelButtonsY;
    }
    return rect;
  };
  // * Отрисовка команд
  _.drawItem = function(index) {
    var rect;
    rect = this.itemRectForText(index);
    this.resetTextColor();
    this.changePaintOpacity(this.isCommandEnabled(index));
    if (index < 3) {
      this._drawIcon(index, rect);
      return this._drawIName(index, rect);
    } else {
      return this.drawText(this.commandName(index), rect.x, rect.y, rect.width, 'center');
    }
  };
  // * Рисует иконку
  _._drawIcon = function(index, rect) {
    var icon;
    icon = this.getProperItemIcon(index);
    return this.contents.drawIcon(rect.x - 2, rect.y + 2, icon);
  };
  // * Пишет название команды
  _._drawIName = function(index, rect) {
    var name;
    name = this.getProperItemName(index);
    return this.drawText(name, rect.x + 38, rect.y - 1, rect.width - 38, 'left');
  };
  // * Получает правильное название команды (либо компонент, либо команда (если ничего не выбрано))
  _.getProperItemName = function(index) {
    var item;
    item = this.farmData.getItemByIndex(index);
    if (item != null) {
      return item.name;
    } else {
      return this.commandName(index);
    }
  };
  
  // * Получает правильную иконку, либо от компонента, либо стандартную (если пусто)
  _.getProperItemIcon = function(index) {
    var item;
    item = this.farmData.getItemByIndex(index);
    if (item != null) {
      return item.iconIndex;
    } else {
      return this.S.NoneIconIndex;
    }
  };
})();

// ■ END Window_FarmSelectorList.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
// * Этот класс отвечает за грядку, хранит все её данные
var GradkaData;

GradkaData = class GradkaData {
  constructor(evId) {
    this.evId = evId;
    this.itemA = 0; // *  Семечко
    this.itemB = 0; // * Вода
    this.itemC = 0; // * Почва
    this.itemD = 0; // * Удобрение
    this._inProcess = false; // * Растёт или нет?
    this._lastSwitch = null; // * Последний активированный переключатель
  }

  
    // * Можно ли потвердить рост? Если есть семечко и вода, то да
  isCanStartGrown() {
    return this.itemA > 0 && this.itemB > 0;
  }

  isInProcess() {
    return this._inProcess === true;
  }

  // * Начать рост (подсчёт времени, переключение А свича)
  startGrown() {
    var now, time;
    this._inProcess = true;
    this._mapId = $gameMap.mapId();
    time = this.getFinalGrownTime();
    now = FarmManager.getCurrentTime();
    this.endTime = now + time;
    this.partTime = now + Math.round(time * 0.3);
    this.partTime2 = now + Math.round(time * 0.6);
    this._changeSwitchTo('A');
    this._removeComponentsFromParty();
  }

  // * Удалить элементы из инвентаря
  _removeComponentsFromParty() {
    $gameParty.loseItem($dataItems[this.itemA], 1);
    $gameParty.loseItem($dataItems[this.itemB], 1);
    if (this.itemC > 0) {
      $gameParty.loseItem($dataItems[this.itemC], 1);
    }
    if (this.itemD > 0) {
      $gameParty.loseItem($dataItems[this.itemD], 1);
    }
  }

  // * Рост закончился?
  isEndProcess() {
    return FarmManager.getCurrentTime() >= this.endTime;
  }

  // * Закончить рост (плод готов, включаем Д свитч)
  endGrownProcess() {
    this._inProcess = false;
    return this._changeSwitchTo('D');
  }

  // * Проверка таймера
  evaluate() {
    if (!this.isInProcess()) {
      return;
    }
    if (this.isEndProcess()) {
      return this.endGrownProcess();
    } else {
      if (this.isPartB()) {
        return this.evaluateToPartB();
      } else if (this.isPartA()) {
        return this.evaluateToPartA();
      }
    }
  }

  // * Получить картинку для текущего свича
  getExtraImagesOnCurrentSelfSwitch() {
    var e, item;
    try {
      item = this.getItemByIndex(0);
      if (this._lastSwitch != null) {
        return item["farmImg" + this._lastSwitch];
      } else {
        return null;
      }
    } catch (error) {
      e = error;
      console.warn(e);
      return null;
    }
  }

  isPartA() {
    return FarmManager.getCurrentTime() >= this.partTime;
  }

  evaluateToPartA() {
    return this._changeSwitchTo('B');
  }

  isPartB() {
    return FarmManager.getCurrentTime() >= this.partTime2;
  }

  evaluateToPartB() {
    return this._changeSwitchTo('C');
  }

  _changeSwitchTo(switchId, value = true) {
    var key;
    this._lastSwitch = switchId;
    key = [this._mapId, this.evId, switchId];
    return $gameSelfSwitches.setValue(key, value);
  }

  // * Когда плод собран игроком (вернуть событие в исходную)
  finale() {
    var ev, item, x, y;
    this._changeSwitchTo('D', false);
    this._changeSwitchTo('C', false);
    this._changeSwitchTo('B', false);
    this._changeSwitchTo('A', false);
    item = this.getFinalResultItem();
    FarmManager.registerNewDinamyItem(item);
    $gameParty.gainItem(item, 1);
    if ($gameSystem._trspupData != null) {
      ev = $gameMap.event(this.evId);
      x = ev.screenX();
      y = ev.screenY();
      $gameSystem._trspupData.push([item, 1, x, y]);
    }
    this._lastSwitch = null;
  }

  // * Генерирует финальный плод (с эффектами компонентов)
  getFinalResultItem() {
    var itemId;
    itemId = this.getResultItem().id;
    return FarmManager.createDinamycItem(itemId, this.itemB, this.itemC, this.itemD, this.itemA);
  }

  // * Получить предмет плод (без эффектов, как он есть, из ДБ)
  getResultItem() {
    var itemA;
    itemA = this.getItemByIndex(0);
    return $dataItems[itemA.farmResult];
  }

  // * Вернёт предмет по index и ID
  getItemByIndex(index) {
    switch (index) {
      case 0:
        return $dataItems[this.itemA];
      case 1:
        return $dataItems[this.itemB];
      case 2:
        return $dataItems[this.itemD];
    }
  }

  //when 3
  //    return $dataItems[@itemD]

    // * Считает время роста (итоговое, с учётом всем предметов)
  getFinalGrownTime() {
    var times;
    times = [0];
    if (this.itemA > 0) {
      times.push(this.getFarmTimeByIndex(0));
    }
    if (this.itemB > 0) {
      times.push(this.getFarmTimeByIndex(1));
    }
    if (this.itemD > 0) {
      //times.push(@getFarmTimeByIndex(2)) if @itemC > 0
      times.push(this.getFarmTimeByIndex(2));
    }
    return times.max();
  }

  // * Время роста для каждого отдельного компонента
  getFarmTimeByIndex(index) {
    var item;
    item = this.getItemByIndex(index);
    if (item == null) {
      return 0;
    }
    if ((item.farmTime != null) && item.farmTime > 0) {
      return item.farmTime;
    }
    return 0;
  }

};


// Generated by CoffeeScript 2.6.1
var FarmManager;

FarmManager = function() {};

(function() {
  var _;
  _ = FarmManager;
  // * Возвращает данные о грядке по событию (или создаёт новые)
  _.getSpotData = function(eventId) {
    var spot;
    spot = $gamePlayer.farmData[eventId];
    if (spot != null) {
      return spot;
    } else {
      $gamePlayer.farmData[eventId] = new GradkaData(eventId);
    }
    return this.getSpotData(eventId);
  };
  // * Возвращает плод из грядки и удаляет её из памяти (можно по новой садить)
  _.getItemFromSpotData = function(eventId) {
    var spot;
    spot = $gamePlayer.farmData[eventId];
    if (spot != null) {
      spot.finale();
      $gamePlayer.farmData[eventId] = null;
      return delete $gamePlayer.farmData[eventId];
    }
  };
  _.isSpotItemExists = function(eventId) {
    return $gamePlayer.isEventIsFarmingItem(eventId);
  };
  // * Создаёт динамический объект из нескольких (складывает эффекты)
  _.createDinamycItem = function(itemId, itemBid, itemCid, itemDid, itemAid) {
    var itemAData, itemBData, itemCData, itemDData, itemData, newId, prefix;
    newId = itemId + "_" + itemBid + "_" + itemCid + "_" + itemDid;
    itemData = JsonEx.stringify($dataItems[itemId]);
    itemData = JsonEx.parse(itemData);
    itemData.id = newId;
    itemData.originId = itemId;
    if (itemBid > 0) {
      itemBData = $dataItems[itemBid];
    }
    if (itemCid > 0) {
      itemCData = $dataItems[itemCid];
    }
    if (itemDid > 0) {
      itemDData = $dataItems[itemDid];
    }
    if (itemAid > 0) {
      itemAData = $dataItems[itemAid];
    }
    if (itemAData != null) {
      this._addDescription(itemData, itemAData);
      itemData.effects.push(...itemAData.effects);
    }
    if (itemBData != null) {
      this._addDescription(itemData, itemBData);
      itemData.effects.push(...itemBData.effects);
    }
    if (itemCData != null) {
      this._addDescription(itemData, itemCData);
      itemData.effects.push(...itemCData.effects);
    }
    if (itemDData != null) {
      this._addDescription(itemData, itemDData);
      itemData.effects.push(...itemDData.effects);
      if (itemDData.meta.farmPrefix > 0) {
        prefix = _.getPrefix(itemDData.meta.farmPrefix);
        itemData.name = prefix + " " + itemData.name;
      }
    }
    if (itemBData != null) {
      if (itemBData.meta.farmAffix != null) {
        itemData.name += " " + itemBData.meta.farmAffix;
      }
    }
    itemData.meta.dynamic = true;
    //console.info itemData
    return itemData;
  };
  _._addDescription = function(itemA, itemB) {
    if (itemB.description == null) {
      return;
    }
    if (itemB.description === "") {
      return;
    }
    if (itemB.description.trim() === "") {
      return;
    }
    itemA.description = itemA.description + "\n" + itemB.description;
  };
  _.registerNewDinamyItem = function(item) {
    return $gamePlayer.registerNewDynamicItem(item);
  };
  _.deleteDinamyItem = function(item) {
    return $gamePlayer.deleteNewDynamicItem(item);
  };
  _.isDinamycItemId = function(id) {
    return id.toString().contains("_");
  };
  _.getPrefix = function(prefixId) {
    return $PKD_Farm.PREFIX[prefixId];
  };
  _.getInfo = function(infoId) {
    return $PKD_Farm.EFFECTS_INFO[infoId];
  };
  _.getCurrentTime = function() {
    return PKD.Utils.getVar($PKD_Farm.GlobalTimeVarId);
  };
  // * Очищает динамические объекты из памяти (которых больше нет в инвентаре игрока)
  _.clearNotUsedDinamics = function() {
    var e, obj, ref, value;
    try {
      ref = $gamePlayer.dinamycFarmItemsDB;
      for (obj in ref) {
        value = ref[obj];
        if ($gameParty.numItems(value) === 0) {
          FarmManager.deleteDinamyItem(value);
        }
      }
    } catch (error) {
      e = error;
      console.warn(e);
    }
  };
})();


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Action.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Action.prototype;
})();

// ■ END Game_Action.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Event.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__setupPageSettings, _;
  //@[DEFINES]
  _ = Game_Event.prototype;
  // * Тут происходит проверка на дополнительное изображение грядки из параметров семечка
  //@[ALIAS]
  ALIAS__setupPageSettings = _.setupPageSettings;
  _.setupPageSettings = function() {
    var imgs, item;
    ALIAS__setupPageSettings.call(this);
    if (FarmManager.isSpotItemExists(this.eventId())) {
      item = FarmManager.getSpotData(this.eventId());
      if (item == null) {
        return;
      }
      if (item._mapId !== $gameMap.mapId()) {
        return;
      }
      imgs = item.getExtraImagesOnCurrentSelfSwitch();
      if (imgs != null) {
        if (imgs[1] != null) {
          return this.setImage(...imgs);
        } else {
          return this.setTileImage(imgs[0]);
        }
      }
    }
  };
})();

// ■ END Game_Event.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Item.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__object, _;
  //@[DEFINES]
  _ = Game_Item.prototype;
  //@[ALIAS]
  ALIAS__object = _.object;
  _.object = function() {
    if (this._isDinamyc(this._itemId)) {
      return $gamePlayer.dynamicItemData(this._itemId);
    } else {
      return ALIAS__object.call(this);
    }
  };
  _._isDinamyc = function(itemId) {
    return FarmManager.isDinamycItemId(itemId);
  };
})();

// ■ END Game_Item.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Party.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__items, _;
  //@[DEFINES]
  _ = Game_Party.prototype;
  //@[ALIAS]
  ALIAS__items = _.items;
  _.items = function() {
    var i, item, items, key, len, list2, ref, value;
    items = ALIAS__items.call(this);
    list2 = [];
    for (i = 0, len = items.length; i < len; i++) {
      item = items[i];
      if (item != null) {
        list2.push(item);
      }
    }
    ref = this._items;
    for (key in ref) {
      value = ref[key];
      if (FarmManager.isDinamycItemId(key)) {
        list2.push($gamePlayer.dynamicItemData(key));
      }
    }
    return list2;
  };
})();

// ■ END Game_Party.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Player.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var ALIAS__initMembers, ALIAS__update, _;
  //@[DEFINES]
  _ = Game_Player.prototype;
  //@[ALIAS]
  ALIAS__initMembers = _.initMembers;
  _.initMembers = function() {
    ALIAS__initMembers.call(this);
    return this.initFarmSystem();
  };
  _.initFarmSystem = function() {
    if (this.farmData == null) {
      this.farmData = {};
    }
    if (this.dinamycFarmItemsDB == null) {
      this.dinamycFarmItemsDB = {};
    }
    return this._farmSystemTimer = 0;
  };
  _.registerNewDynamicItem = function(item) {
    if (this.dinamycFarmItemsDB[item.id] == null) {
      return this.dinamycFarmItemsDB[item.id] = item;
    }
  };
  _.deleteNewDynamicItem = function(item) {
    if (this.isContainsDynamicItem(item.id)) {
      return delete this.dinamycFarmItemsDB[item.id];
    }
  };
  _.isContainsDynamicItem = function(itemId) {
    return (this.dinamycFarmItemsDB != null) && (this.dinamycFarmItemsDB[itemId] != null);
  };
  _.dynamicItemData = function(itemId) {
    return this.dinamycFarmItemsDB[itemId];
  };
  _.isEventIsFarmingItem = function(eventId) {
    return this.farmData[eventId] != null;
  };
  //@[ALIAS]
  ALIAS__update = _.update;
  _.update = function(sceneActive) {
    ALIAS__update.call(this, sceneActive);
    this._farmSystemTimer++;
    if (this._farmSystemTimer >= 60) {
      this._farmSystemTimer = 0;
      return this._checkTimeOnAllFarmItems();
    }
  };
  _._checkTimeOnAllFarmItems = function() {
    var obj, ref, value;
    ref = this.farmData;
    for (obj in ref) {
      value = ref[obj];
      if (value == null) {
        continue;
      }
      if (value.isInProcess()) {
        value.evaluate();
      }
    }
  };
})();

// ■ END Game_Player.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_System.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__onAfterLoad, _;
  //@[DEFINES]
  _ = Game_System.prototype;
  //@[ALIAS]
  ALIAS__onAfterLoad = _.onAfterLoad;
  _.onAfterLoad = function() {
    ALIAS__onAfterLoad.call(this);
    return $gamePlayer.initFarmSystem();
  };
})();

// ■ END Game_System.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Farm.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Farm.prototype;
  _._createWindows = function() {
    this._createSelectorListWindow();
    this._createResultInfoWindow();
    this._createHelpWindow();
    this._createFarmListWindow();
    return this._windowSettings();
  };
  // * Создаёт окно выбора компонента
  _._createSelectorListWindow = function() {
    var p;
    p = this.S.SelectorWindowPosition;
    this.wSelector = new Window_FarmSelectorList(p[0], p[1]);
    return this.addWindow(this.wSelector);
  };
  
  // * Создаёт окно с результатом (итоговый плод)
  _._createResultInfoWindow = function() {
    var p;
    p = this.S.InfoWindowPosition;
    this.wResult = new Window_FarmResult(p[0], p[1], 400, 350);
    return this.addWindow(this.wResult);
  };
  // * Создаёт окно помощи (описание выбранного компонента)
  _._createHelpWindow = function() {
    this._helpWindow = new Window_Help();
    this._helpWindow.width = this.S.DescriptionWindowWH[0];
    this._helpWindow.height = this.S.DescriptionWindowWH[1];
    this._helpWindow.x = this.S.DescriptionWindowPosition[0];
    this._helpWindow.y = this.S.DescriptionWindowPosition[1];
    this._helpWindow.standardFontSize = function() {
      return 18;
    };
    this._helpWindow.hide();
    this._helpWindow.close();
    return this.addWindow(this._helpWindow);
  };
  // * Создаёт окно выбора компонентов (предметов)
  _._createFarmListWindow = function() {
    var p;
    p = this.S.ListWindowPosition;
    this.wList = new Window_FarmItemList(p[0], p[1], 400, 350);
    this.wList.hide();
    this.wList.close();
    return this.addWindow(this.wList);
  };
  _._windowSettings = function() {
    return this.wList.setHelpWindow(this._helpWindow);
  };
})();

// ■ END Scene_Farm.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Farm.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Farm.prototype;
  // * Установка комманд (кнопок) и действий по их нажатию
  _._registerCommands = function() {
    this.wSelector.setHandler('partA', this.commandItemA.bind(this));
    this.wSelector.setHandler('partB', this.commandItemB.bind(this));
    this.wSelector.setHandler('partC', this.commandItemC.bind(this));
    this.wSelector.setHandler('partD', this.commandItemD.bind(this));
    this.wSelector.setHandler('cancel', this.popScene.bind(this));
    this.wSelector.setHandler('ok', this.commandStartGrown.bind(this));
    return this.wList.setHandler('ok', this.commandOnItemSelected.bind(this));
  };
  _.commandItemA = function() {
    this.hideInfoWindow();
    return this.showItemSelectWindow(0);
  };
  _.commandItemB = function() {
    this.hideInfoWindow();
    return this.showItemSelectWindow(1);
  };
  _.commandItemC = function() {
    this.hideInfoWindow();
    return this.showItemSelectWindow(2);
  };
  _.commandItemD = function() {
    this.hideInfoWindow();
    return this.showItemSelectWindow(3);
  };
  // * Когда выбран предмет для компонента в списке предметов
  _.commandOnItemSelected = function() {
    this.wList.selectItem();
    this.wSelector.refresh();
    this.wResult.refresh();
    return this.popMenu();
  };
  _.hideInfoWindow = function() {
    return this.wResult.close();
  };
  // * Показать окно выбора предмета для компонента
  _.showItemSelectWindow = function(catIndex) {
    this._inSecondPhase = true;
    this.wList.setFarmData(this.wSelector.farmData);
    this.wList.setCategory(catIndex);
    this.wList.show();
    this.wList.open();
    return this.wList.onShow();
  };
  _.popMenu = function() {
    this.hideItemSelectWindow();
    return this.showInfoWindow();
  };
  _.hideItemSelectWindow = function() {
    this.wList.onClose();
    return this.wList.close();
  };
  _.showInfoWindow = function() {
    this.wResult.open();
    return this.wSelector.activate();
  };
  _.commandStartGrown = function() {
    this.wSelector.startGrown();
    return this.popScene();
  };
})();

// ■ END Scene_Farm.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Window_FarmResult.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var _;
  //@[DEFINES]
  _ = Window_FarmResult.prototype;
  // * Рисует информацию о результате
  _._drawAllInfo = function() {
    this._drawResultItemLine();
    this.drawYStart += 80;
    this._drawEffects();
    this.drawYStart += 190;
    this.addSeparateLine(this.drawYStart);
    this.drawYStart += 5;
    return this._drawTime();
  };
  // * Рисует название и иконку плода
  _._drawResultItemLine = function() {
    var tempItem;
    this.changePaintOpacity(true);
    tempItem = this.farmData.getFinalResultItem();
    return this.drawItemName(tempItem, 0, this.drawYStart, this.width - 20);
  };
  // * Рисует эффекты (общий метод)
  _._drawEffects = function() {
    var effectBase;
    this.drawEffectsTitle();
    //@drawYStart += 20
    effectBase = new Sprite(new Bitmap(360, 200));
    //effectBase.bitmap.fillAll KDCore.Color.BLACK
    //effectBase.opacity = 150
    effectBase.move(20, this.drawYStart);
    this.drawYEffect = 0;
    this.add(effectBase);
    this.effectBaseW = new Window_Base(0, 0, 360, 200);
    this.effectBaseW.setBackgroundType(1);
    this.effectBaseW.standardFontSize = function() {
      return 16;
    };
    effectBase.addChild(this.effectBaseW);
    return this._drawAllEffects();
  };
  // * Картинка заголовок Эффекты
  _.drawEffectsTitle = function() {
    this._headerE = PKD.FARM.SPRITE("Header3");
    this._headerE.move(this.S.Header3ImgPosition);
    return this.addChild(this._headerE);
  };
  // * Рисует эффекты с каждого компонента
  _._drawAllEffects = function() {
    this._drawEffectsFrom(this.farmData.itemA);
    this._drawEffectsFrom(this.farmData.itemB);
    this._drawEffectsFrom(this.farmData.itemC);
    return this._drawEffectsFrom(this.farmData.itemD);
  };
  // * Извлекает эффект с предмета и добавлет его как строчку текста
  _._drawEffectsFrom = function(itemId) {
    var effectText, item;
    item = $dataItems[itemId];
    if (item == null) {
      return;
    }
    if ((item.meta != null) && item.meta.farmEffect > 0) {
      effectText = FarmManager.getInfo(item.meta.farmEffect);
      if ((effectText != null) && effectText.trim() !== "") {
        return this._drawEffectLine(effectText);
      }
    }
  };
  // * Пишет текст эффекта предмета и сдвигает "курсор" ниже
  _._drawEffectLine = function(text) {
    this.effectBaseW.drawTextEx(text, 0, this.drawYEffect);
    return this.drawYEffect += this.effectBaseW.lineHeight();
  };
  // * Рисует время роста
  _._drawTime = function() {
    var t, textSpr;
    textSpr = new Sprite(new Bitmap(this.width - 20, 30));
    textSpr.move(10, this.drawYStart);
    textSpr.bitmap.fontSize = 20;
    textSpr.bitmap.textColor = KDCore.Color.FromHex(this.S.LineColor).CSS;
    t = this.farmData.getFinalGrownTime();
    textSpr.bitmap.drawTextFull('{Время роста: }' + t, 'center');
    return this.add(textSpr);
  };
  
  // * рисует линию
  _.addSeparateLine = function(y, extraH) {
    var b, color, h, line, shadow, w, x;
    x = 36;
    w = this.width - 108;
    h = 2;
    if (extraH === true) {
      h += 1;
    }
    line = new Sprite(new Bitmap(w, h + 2));
    color = KDCore.Color.FromHex(this.S.LineColor).CSS;
    b = line.bitmap;
    b.fillRect(0, 0, w, h, color);
    shadow = KDCore.Color.FromHex("#494453").CSS;
    b.fillRect(0, h, w, 1, shadow);
    line.move(x, y);
    return this.add(line);
  };
})();

// ■ END Window_FarmResult.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Boot.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Boot.prototype;
})();

// ■ END Scene_Boot.coffee
//---------------------------------------------------------------------------
//@[ALIAS]
/*ALIAS__start = _.start
_.start = ->
    ALIAS__start.call(@, ...arguments)
    PKD_Farm.LoadPluginSettings()
    return*/

//Plugin PKD_Farm builded by PKD PluginBuilder 2.2 - 11.11.2023