/*:
 * @plugindesc Система обустройства дома
 * @author Pheonix KageDesu
 *
 * @help
 * 
 * Файл настройки: data \ $PKD_House.json
 * Графика img\ pkd_house
 * 
 * Команды плагина:
 * 
 * ShowHouseInfo - показать шкалу
 * HideHouseInfo - скрыть шкалу
 * StartHouseSystem - начать растановку предметов
 * RefreshHouseSystem - пересчитать значение юута в доме
 * RiseHouse X - поднять (опустить) уют на X (-X)
 * ApplyHouseState - применить состояние в зависимости от текущего уюта
 * 
 * Вызовы скриптов:
 * 
 * HouseManager.currentUValue - вернёт текущее значение уюта
 * 
 * $gamePlayer._extraUValue = 0 - установить в 0 уют, который был изменён
 *  командой плагина RiseHouse (сбросить короче)
 * 
 * Note для предметов:
 * 
 * <houseItem:X> - предмет для размещения, X - уровень уюта.
 * Если предмет декорация, то замечто X 0 (ноль)
 * 
 * Note для событий:
 * <HOUSE:X>, X - id предмета из базы данных (это событие будет при размещении
 * этого предмета)
 * 
 * 
 * Комментарии для событий:
 * houseDamage_X - минус к уюту (X - значение). Для создания событий поломок
 * 
 */
//@[CODE STANDARD X3]

/* jshint -W097 */
/* jshint -W117 */


var Imported = Imported || {};

var PKD = PKD || {};
PKD.LIBS = PKD.LIBS || {};

PKD.HOUSE = {};

DataManager._databaseFiles.push({
    name: '$PKD_House',
    src: 'PKD_House.json'
});

PKD.HOUSE.SPRITE = function (filename) {
    return new Sprite(PKD.HOUSE.IMG(filename));
};

PKD.HOUSE.IMG = function (filename) {
    return ImageManager.loadBitmap('img/pictures/', filename, 0, true);
};

PKD.Scene = function() {
    return SceneManager._scene;
};


// Generated by CoffeeScript 2.5.1
var Scene_Housing;

Scene_Housing = class Scene_Housing extends Scene_Base {
  constructor() {
    super();
  }

};

// Generated by CoffeeScript 2.5.1
var HouseManager;

HouseManager = function() {};

(function() {
  var _;
  _ = HouseManager;
  _.InitOnMap = function() {
    this.currentUValue = 0;
    PKD.Scene().createHouseGauge();
    this.gauge = PKD.Scene().getHouseGauge();
    return this.RefreshMapAll();
  };
  _.RefreshMapAll = function() {
    var ev, events, i, len;
    events = $gameMap.getNotUsedHousingEvents();
    for (i = 0, len = events.length; i < len; i++) {
      ev = events[i];
      ev.locate(-100, -100);
    }
    return this.RefreshOnMap();
  };
  _.RefreshOnMap = function() {
    this.currentUValue = 0;
    this.CalculateUByItems();
    this.CalculateUByElementsOnMap();
    return this.RefreshFinalValue();
  };
  _.RefreshFinalValue = function() {
    this.currentUValue += $gamePlayer.h_getExtraUValue();
    if (this.currentUValue < 0) {
      this.currentUValue = 0;
    }
    if (this.currentUValue > 100) {
      this.currentUValue = 100;
    }
    return this.RefreshGauge();
  };
  _.CalculateUByItems = function() {
    var ev, i, len, pos, uByEvents, value;
    uByEvents = $gameMap.getUsedHousingEvents();
    value = 0;
    for (i = 0, len = uByEvents.length; i < len; i++) {
      ev = uByEvents[i];
      value += ev.getHousingUValue();
      pos = $gamePlayer.h_getPlacedEventPositionById(ev.eventId());
      ev.locate(pos[0], pos[1]);
    }
    return this.currentUValue += value;
  };
  _.CalculateUByElementsOnMap = function() {
    var dmg, ev, i, len, value;
    dmg = $gameMap.getEventsWithDamage();
    value = 0;
    for (i = 0, len = dmg.length; i < len; i++) {
      ev = dmg[i];
      value += ev.houseSystemDamage;
    }
    return this.currentUValue -= value;
  };
  _.RefreshGauge = function() {
    this.gauge.drawGauge(this.currentUValue / 100);
    this.gauge.drawText(this.currentUValue);
    return this.gauge.drawInfo("");
  };
  _.ShowGauge = function() {
    return this.gauge.visible = true;
  };
  _.HideGauge = function() {
    return this.gauge.visible = false;
  };
  _.GetPlacementsFor = function(itemId) {
    var event;
    event = $gameMap.getHousingEventForItem(itemId);
    if (event == null) {
      return [];
    }
    return this.GetPlacementsForEventId(event.eventId());
  };
  _.GetPlacementsForEventId = function(eventId) {
    var i, item, len, ref;
    ref = $PKD_House.PlaceDefinition;
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      if (item.eventId === eventId) {
        return item.placements;
      }
    }
    return [];
  };
  _.GetHousingEventOnPlacementSpot = function(pos) {
    var ev, i, len, placed;
    placed = $gameMap.getUsedHousingEvents();
    for (i = 0, len = placed.length; i < len; i++) {
      ev = placed[i];
      if (ev.x === pos[0] && ev.y === pos[1]) {
        return ev;
      }
    }
    return null;
  };
  _.LocateNewHouseEvent = function(event, spotPos) {
    event.locate(spotPos[0], spotPos[1]);
    return $gamePlayer.h_placeEvent(event.eventId(), spotPos);
  };
  _.DeplaceHouseEvent = function(event) {
    event.locate(-100, -100);
    return $gamePlayer.h_removeEvent(event.eventId());
  };
  _.RefreshGaugeBuffStates = function() {
    var state;
    state = this.GetGaugeZoneState();
    if (state > 0 && ($dataStates[state] != null)) {
      return $gameParty.leader().addState(state);
    }
  };
  _.GetGaugeZoneInfo = function() {
    var item;
    item = this._getGaugeZoneItem();
    if (item != null) {
      return item[0];
    }
    return "";
  };
  _.GetGaugeZoneState = function() {
    var item;
    item = this._getGaugeZoneItem();
    if (item != null) {
      return item[1];
    }
    return 0;
  };
  _._getGaugeZoneItem = function() {
    var value;
    value = Math.ceil(this.currentUValue / 5);
    return $PKD_House.GaugeZones[value];
  };
})();

// Generated by CoffeeScript 2.5.1



(function(){
    
    //@[ALIAS]
    var _Game_Interpreter_pluginCommand_3434 = Game_Interpreter.prototype.pluginCommand;
    Game_Interpreter.prototype.pluginCommand = function (command, args) {
        _Game_Interpreter_pluginCommand_3434.call(this, command, args);
        if (command === 'ShowHouseInfo') {
            try {

                HouseManager.ShowGauge();

            } catch (e) {
                console.warn(e);
            }
        } else if (command === 'HideHouseInfo') {
            try {

                HouseManager.HideGauge();

            } catch (e) {
                console.warn(e);
            }
        } else if (command === 'StartHouseSystem') {
            try {

                //SceneManager.push(Scene_Housing);
                SceneManager._scene.startHousing();
                this._waitMode = "Housing";

            } catch (e) {
                console.warn(e);
            }
        } else if (command === 'RefreshHouseSystem') {
            try {

                HouseManager.RefreshOnMap();
                setTimeout(() => {
                    HouseManager.RefreshOnMap();
                }, 200);

            } catch (e) {
                console.warn(e);
            }
        } else if (command === 'RiseHouse') {
            try {

                var value = parseInt(args[0]);
                $gamePlayer.h_modExtraUValue(value);
                HouseManager.RefreshOnMap();

            } catch (e) {
                console.warn(e);
            }
        } else if (command === 'ApplyHouseState') {
            try {

                HouseManager.RefreshGaugeBuffStates();

            } catch (e) {
                console.warn(e);
            }
        }
    };

    //@[ALIAS]
    var _alias_Game_Interpreter_updateWaitMode = Game_Interpreter.prototype.updateWaitMode;
    Game_Interpreter.prototype.updateWaitMode = function () {
        var waiting = false;
        if(this._waitMode == 'Housing') {
            waiting = (SceneManager._scene._inHousingMode == true);
            if(!waiting)
                this._waitMode = '';
            else
                return true;
        }
        return _alias_Game_Interpreter_updateWaitMode.call(this);
    };


    PKD.HOUSE.getEventCommentValue = function (commentCode, list) {

        try {
            if (list && list.length > 1) {
                var i = 0;
                while (i < list.length) {
                    var item = list[i++];
                    if (!item) continue;
                    if (item.code == 108) {
                        var comment = item.parameters[0];
                        if (comment.contains(commentCode)) {
                            return comment;
                        }
                    }
                }
            }
        } catch (e) {
            console.warn(e);
        }

        return null;
    };

})();
// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Housing.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__isMenuEnabled, ALIAS__processMapTouch, ALIAS__update, _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  _._hh_create = function() {
    $gameTemp._placementDone = false;
    this._placementsSprites = [];
    this._hh_init();
    //Scene_Base::create.call @
    //Scene_MenuBase::createBackground.call @
    //@_createBackgoundImage()
    this._createBackMap();
    //@createWindowLayer()
    this._hh_createWindows();
    return this._hh_createHousingGauge();
  };
  _._hh_init = function() {
    return this.S = $PKD_House;
  };
  // * Создаёт картинку фона (или ничего, если null)
  _._createBackgoundImage = function() {
    var bakImg;
    if (this.S.BackGroundImg != null) {
      bakImg = PKD.HOUSE.SPRITE(this.S.BackGroundImg);
      bakImg.move(this.S.BackGroundImgPositon);
      return this.addChild(bakImg);
    }
  };
  _._createBackMap = function() {
    this._housingBase = new Sprite();
    this._housingBase.visible = false;
    this.addChild(this._housingBase);
  };
  //@[ALIAS]
  //@_backgroundMap = new Sprite(SceneManager._backgroundBitmap2)
  //@_housingBase.addChild @_backgroundMap
  ALIAS__update = _.update;
  _.update = function() {
    ALIAS__update.call(this);
    if (!this._inHousingMode) {
      return;
    }
    if (this._hh_isExit() && this._inPlacementMode === true) {
      this.hh_endPlacementMode();
    }
    if (this._inPlacementMode === true) {
      return this._hh_updatePlacementMove();
    }
  };
  //@[ALIAS]
  ALIAS__isMenuEnabled = _.isMenuEnabled;
  _.isMenuEnabled = function() {
    if (this._inHousingMode) {
      return false;
    } else {
      return ALIAS__isMenuEnabled.call(this);
    }
  };
  
  //@[ALIAS]
  ALIAS__processMapTouch = _.processMapTouch;
  _.processMapTouch = function() {
    if (this._inHousingMode) {
      return;
    }
    return ALIAS__processMapTouch.call(this);
  };
  _._hh_isExit = function() {
    return Input.isTriggered('cancel') || TouchInput.isCancelled();
  };
})();

// ■ END Scene_Housing.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Housing.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  _._hh_createWindows = function() {
    this.hh_createCategoryWindow();
    return this.hh_createItemListWindow();
  };
  _.hh_createCategoryWindow = function() {
    this._hh_categoryWindow = new Window_HousingItemsCategories();
    this._hh_categoryWindow.setHandler('ok', this.hh_onCategoryOk.bind(this));
    this._hh_categoryWindow.setHandler('cancel', this.hh_cancelHousing.bind(this));
    this._hh_categoryWindow.x = this.S.Windows.position[0];
    this._hh_categoryWindow.y = this.S.Windows.position[1];
    return this.addWindow(this._hh_categoryWindow);
  };
  _.hh_createItemListWindow = function() {
    this._hh_itemsWindow = new Window_Housing_ItemList();
    this._hh_itemsWindow.setHandler('ok', this.hh_onItemOk.bind(this));
    this._hh_itemsWindow.setHandler('cancel', this.hh_onItemCancel.bind(this));
    this._hh_itemsWindow.x = this.S.Windows.position[0];
    this._hh_itemsWindow.y = this.S.Windows.position[1] + this._hh_categoryWindow.height;
    this._hh_categoryWindow.setItemWindow(this._hh_itemsWindow);
    this._hh_itemsWindow.refresh();
    return this.addWindow(this._hh_itemsWindow);
  };
  _.hh_onCategoryOk = function() {
    this._hh_itemsWindow.activate();
    return this._hh_itemsWindow.selectLast();
  };
  _.hh_cancelHousing = function() {
    var ref;
    this._inHousingMode = false;
    this._hh_categoryWindow.parent.removeChild(this._hh_categoryWindow);
    this._hh_itemsWindow.parent.removeChild(this._hh_itemsWindow);
    this._hh_categoryWindow = null;
    this._hh_itemsWindow = null;
    this._housingBase.visible = false;
    this.removeChild(this._housingBase);
    if ($gameTemp._placementDone === false) {
      if ((ref = this._placementEvent) != null) {
        ref.setPosition(-100, -100);
      }
      $gamePlayer.center($gamePlayer.x, $gamePlayer.y);
    } else {
      setTimeout(function() {
        return $gamePlayer.center($gamePlayer.x, $gamePlayer.y);
      }, 300);
    }
    this._placementsSprites = [];
  };
  _.hh_onItemOk = function() {
    $gameTemp._lastHousingItem = this._hh_itemsWindow.item();
    if ($gameTemp._lastHousingItem == null) {
      this._hh_itemsWindow.activate();
      return;
    }
    return this.hh_goToThePlacementMode();
  };
  _.hh_onItemCancel = function() {
    this._hh_itemsWindow.deselect();
    return this._hh_categoryWindow.activate();
  };
})();

// ■ END Scene_Housing.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Housing.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
//$[ENCODE]
//$[ENCODE]
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  //_._createHousingInfo
  _._hh_createHousingGauge = function() {
    this.shg = new Sprite_HouseGauge();
    //@shg.visible = false
    return this._housingBase.addChild(this.shg);
  };
  _.hh_goToThePlacementMode = function() {
    this._inPlacementMode = true;
    this._hh_categoryWindow.hide();
    this._hh_itemsWindow.hide();
    this._housingBase.visible = true;
    return this._hh_determinatePlacementItem();
  };
  _.hh_endPlacementMode = function() {
    var ref;
    $gamePlayer.center($gamePlayer.x, $gamePlayer.y);
    this._inPlacementMode = false;
    this._hh_destroyPlacements();
    this._hh_categoryWindow.show();
    this._hh_itemsWindow.show();
    if ($gameTemp._placementDone === false) {
      if ((ref = this._placementEvent) != null) {
        ref.setPosition(-100, -100);
      }
    }
    return this.hh_onCategoryOk();
  };
  _._hh_destroyPlacements = function() {
    if (this._placementsSprite != null) {
      this._housingBase.removeChild(this._placementsSprite);
      this._placementsSprite = null;
      this._placementsSprites = [];
    }
    this._hh_destroyPlacementEventSpr();
  };
  _._hh_determinatePlacementItem = function() {
    var item, places;
    item = $gameTemp._lastHousingItem;
    if (item == null) {
      this.hh_endPlacementMode();
    }
    this._placementEvent = $gameMap.getHousingEventForItem(item.id);
    places = HouseManager.GetPlacementsFor(item.id);
    this._hh_createPlacements(places);
    this._placementIndex = 0;
    return this._hh_refreshItemPlacement();
  };
  _._hh_createPlacements = function(_placements) {
    this._placements = _placements;
    return this._hh_drawPlacements();
  };
  _._hh_drawPlacements = function() {
    var c, i, len, p, ref, s;
    this._placementsSprite = new Sprite();
    c = new Game_CharacterBase();
    ref = this._placements;
    for (i = 0, len = ref.length; i < len; i++) {
      p = ref[i];
      s = PKD.HOUSE.SPRITE("Placement");
      c.setPosition(p[0], p[1] - 1);
      s.move(c.screenX() - 24, c.screenY());
      s._placement = p;
      this._placementsSprite.addChild(s);
      this._placementsSprites.push(s);
    }
    this._housingBase.addChild(this._placementsSprite);
    //@_spriteset._tilemap.addChild @_placementsSprite
    c = null;
  };
  _._hh_refreshPlacementsPositions = function() {
    var c, i, len, p, ref, s;
    c = new Game_CharacterBase();
    ref = this._placements;
    for (i = 0, len = ref.length; i < len; i++) {
      p = ref[i];
      c.setPosition(p[0], p[1] - 1);
      s = this._placementsSprites.find(function(spr) {
        return spr._placement === p;
      });
      s.move(c.screenX() - 24, c.screenY());
    }
    c = null;
  };
  _._hh_updatePlacementMove = function() {
    var pressed;
    if (this._placements.length > 1) {
      pressed = false;
      if (Input.isTriggered('left')) {
        this._placementIndex--;
        SoundManager.playCursor();
        pressed = true;
      }
      if (Input.isTriggered('right')) {
        SoundManager.playCursor();
        this._placementIndex++;
        pressed = true;
      }
      if (this._placementIndex < 0) {
        this._placementIndex = this._placements.length - 1;
      }
      if (this._placementIndex >= this._placements.length) {
        this._placementIndex = 0;
      }
      if (pressed) {
        this._hh_refreshItemPlacement();
      }
    } else {
      if (Input.isTriggered('left') || Input.isTriggered('right')) {
        SoundManager.playBuzzer();
      }
    }
    if (Input.isTriggered('ok') || TouchInput.isTriggered()) {
      SoundManager.playOk();
      return this._hh_placeEventOnNewSpot();
    }
  };
  _._hh_refreshItemPlacement = function() {
    var pos;
    this._hh_destroyPlacementEventSpr();
    this._placementEventSpr = new Sprite_Character(this._placementEvent);
    this._housingBase.addChild(this._placementEventSpr);
    pos = this._placements[this._placementIndex];
    this._placementEvent.locate(pos[0], pos[1]);
    //"SCROOL".p()
    //$gameMap.setDisplayPos(pos[0], pos[1])
    $gamePlayer.center(pos[0], pos[1]);
    this._hh_refreshPlacementsPositions();
    this._hh_refreshUValueGaugeByPlacement();
  };
  _._hh_destroyPlacementEventSpr = function() {
    if (this._placementEventSpr != null) {
      this._housingBase.removeChild(this._placementEventSpr);
      return this._placementEventSpr = null;
    }
  };
  _._hh_placeEventOnNewSpot = function() {
    var item, oldItem, spotPos;
    spotPos = this._placements[this._placementIndex];
    HouseManager.LocateNewHouseEvent(this._placementEvent, spotPos);
    item = $gameTemp._lastHousingItem;
    $gameParty.gainItem(item, -1);
    $gameTemp._lastHousingItem = null;
    if (this.__tempEventOnSpot != null) {
      HouseManager.DeplaceHouseEvent(this.__tempEventOnSpot);
      oldItem = $dataItems[this.__tempEventOnSpot.getHousingItemId()];
      if (oldItem != null) {
        $gameParty.gainItem(oldItem, 1);
      }
    }
    HouseManager.RefreshOnMap();
    $gameTemp._placementDone = true;
    $gameTemp._placeHouseAnimationEvent = this._placementEvent;
    if ($gameTemp._placeHouseAnimationEvent != null) {
      $gameTemp._placeHouseAnimationEvent.requestAnimation($PKD_House.placeAnimtionId);
      $gameTemp._placeHouseAnimationEvent = null;
    }
    return this.hh_cancelHousing();
  };
  _._hh_refreshUValueGaugeByPlacement = function() {
    var current, eventOnSpot, eventUValue, existsValue, spotPos;
    current = HouseManager.currentUValue;
    this._hh_refreshUValueOnGauge(current, 0, 0);
    spotPos = this._placements[this._placementIndex];
    eventOnSpot = HouseManager.GetHousingEventOnPlacementSpot(spotPos);
    eventUValue = this._placementEvent.getHousingUValue();
    if (eventOnSpot != null) {
      this.__tempEventOnSpot = eventOnSpot;
      existsValue = eventOnSpot.getHousingUValue();
      if (eventUValue !== existsValue) {
        if (eventUValue > existsValue) {
          this._hh_refreshUValueOnGauge(current, eventUValue - existsValue, 1);
        } else {
          this._hh_refreshUValueOnGauge(current, existsValue - eventUValue, 2);
        }
      }
    } else {
      this.__tempEventOnSpot = null;
      if (eventUValue > 0) {
        this._hh_refreshUValueOnGauge(current, eventUValue, 1);
      }
    }
  };
  _._hh_refreshUValueOnGauge = function(current, value, colorCode) {
    var newStateItem, newValue;
    if (value === 0) {
      this.shg.drawGauge(current / 100);
    } else {
      this.shg.drawGaugeAddon(current / 100, value / 100, colorCode);
    }
    newValue = current;
    if (colorCode === 1) {
      newValue += value;
    } else {
      newValue -= value;
    }
    this.shg.drawText(newValue, colorCode);
    newStateItem = $PKD_House.GaugeZones[Math.ceil(newValue / 5)];
    if (newStateItem != null) {
      return this.shg.drawInfo(newStateItem[0], colorCode);
    } else {
      return this.shg.drawInfo("", 0);
    }
  };
})();

// ■ END Scene_Housing.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Sprite_HouseGauge.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
var Sprite_HouseGauge;

Sprite_HouseGauge = class Sprite_HouseGauge extends Sprite {
  constructor() {
    super();
    this._create();
  }

  _create() {
    var pos;
    this.S = $PKD_House.Gauge;
    this.fillMargin = 4;
    this._createBackground();
    this._createFill();
    this._createText();
    this._createInfoText();
    this._createTMargin();
    pos = this.S.position;
    return this.move(pos[0], pos[1]);
  }

  _createFill() {
    this._fillImg = new Sprite(new Bitmap(this.S.size[0] - this.fillMargin, this.S.size[1] - this.fillMargin));
    this._fillImg.bitmap.fillAll(KDCore.Color.FromHex(this.S.fillColor));
    this._fill = new Sprite(new Bitmap(this.S.size[0] - this.fillMargin, this.S.size[1] - this.fillMargin));
    this.addChild(this._fill);
    this._fill.move(this.fillMargin / 2, this.fillMargin / 2);
    return this.drawGauge(1);
  }

  _createTMargin() {
    this._tMargin = new Sprite();
    this._tMargin.bitmap = new Bitmap(this.S.size[0] - this.fillMargin, this.S.size[1] - this.fillMargin);
    this._tMargin.move(this.fillMargin / 2, this.fillMargin / 2);
    return this.addChild(this._tMargin);
  }

  drawGauge(percent) {
    var ref, w;
    if (this._fill == null) {
      return;
    }
    if ((ref = this._tMargin) != null) {
      ref.bitmap.clear();
    }
    this._fill.bitmap.clear();
    w = (this.S.size[0] - this.fillMargin) * percent;
    return this._fill.bitmap.blt(this._fillImg.bitmap, 0, 0, w, this.S.size[1] - this.fillMargin, 0, 0);
  }

  _createBackground() {
    this.bitmap = new Bitmap(this.S.size[0], this.S.size[1]);
    this.back = new Sprite(new Bitmap(this.S.size[0], this.S.size[1]));
    this.back.bitmap.fillAll(KDCore.Color.FromHex(this.S.backcolor));
    this.back.opacity = this.S.backOpacity;
    return this.addChild(this.back);
  }

  _createText() {
    this._text = new Sprite(new Bitmap(this.S.size[0], this.S.size[1]));
    return this.addChild(this._text);
  }

  drawText(text, colorMode) {
    if (this._text == null) {
      return;
    }
    this._text.bitmap.clear();
    this._text.bitmap.fontSize = this.S.textSize;
    this._text.bitmap.outlineWidth = 4;
    this._text.bitmap.textColor = KDCore.Color.WHITE.CSS;
    if (colorMode === 1) {
      this._text.bitmap.textColor = KDCore.Color.GREEN.CSS;
    } else if (colorMode === 2) {
      this._text.bitmap.textColor = KDCore.Color.RED.CSS;
    }
    return this._text.bitmap.drawTextFull(text + "/100", 'center');
  }

  _createInfoText() {
    this._text2 = new Sprite(new Bitmap(this.S.size[0], this.S.size[1]));
    this._text2.bitmap.fontSize = this.S.infoTextSize;
    this.addChild(this._text2);
    this._text2.move(this.S.infoTextPos[0], this.S.infoTextPos[1]);
  }

  //@_text2.bitmap.outlineWidth = 2
  drawInfo(text, colorMode) {
    if (this._text2 == null) {
      return;
    }
    this._text2.bitmap.clear();
    this._text2.bitmap.textColor = KDCore.Color.WHITE.CSS;
    if (colorMode === 1) {
      this._text2.bitmap.textColor = KDCore.Color.GREEN.CSS;
    } else if (colorMode === 2) {
      this._text2.bitmap.textColor = KDCore.Color.RED.CSS;
    }
    return this._text2.bitmap.drawTextFull(text, 'center');
  }

  drawGaugeAddon(current, newValue, colorMode) {
    var bit, color, wEnd, wLen;
    this.drawGauge(current);
    this._tMargin.bitmap.clear();
    wLen = (this.S.size[0] - this.fillMargin) * newValue;
    wEnd = (this.S.size[0] - this.fillMargin) * current;
    bit = new Bitmap(wLen, this.S.size[1] - this.fillMargin);
    this._tMargin.bitmap = bit;
    color = KDCore.Color.FromHex(this.S.fillColor);
    if (colorMode === 1) {
      color = KDCore.Color.GREEN;
      this._tMargin.x = wEnd;
    } else if (colorMode === 2) {
      color = KDCore.Color.RED;
      this._tMargin.x = wEnd - wLen + 4;
    }
    return this._tMargin.bitmap.fillAll(color);
  }

};

// ■ END Sprite_HouseGauge.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Event.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__setupPage, _;
  //@[DEFINES]
  _ = Game_Event.prototype;
  //@[ALIAS]
  ALIAS__setupPage = _.setupPage;
  _.setupPage = function() {
    var e, value;
    ALIAS__setupPage.call(this);
    try {
      this.houseSystemDamage = 0;
      if (this.page() == null) {
        return;
      }
      value = PKD.HOUSE.getEventCommentValue("houseDamage", this.list());
      if (value != null) {
        return this.houseSystemDamage = parseInt(value.split("_")[1]);
      }
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  _.getHousingItemId = function() {
    if ((this.event().meta != null) && (this.event().meta.HOUSE != null)) {
      return parseInt(this.event().meta.HOUSE);
    } else {
      return 0;
    }
  };
  _.getHousingUValue = function() {
    var item, itemId;
    itemId = this.getHousingItemId();
    if (itemId <= 0) {
      return 0;
    }
    item = $dataItems[itemId];
    return parseInt(item.meta.houseItem);
  };
})();

// ■ END Game_Event.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Map.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Map.prototype;
  _.getNotUsedHousingEvents = function() {
    var housing, used;
    used = $gamePlayer.h_getPlacedEventIds();
    housing = this.getEventsForHousing();
    return housing.filter(function(e) {
      return !used.contains(e.eventId());
    });
  };
  _.getUsedHousingEvents = function() {
    var housing, used;
    used = $gamePlayer.h_getPlacedEventIds();
    housing = this.getEventsForHousing();
    return housing.filter(function(e) {
      return used.contains(e.eventId());
    });
  };
  _.getEventsForHousing = function() {
    return this.events().filter(function(e) {
      return e.getHousingItemId() > 0;
    });
  };
  _.getEventsWithDamage = function() {
    return this.events().filter(function(e) {
      return e.houseSystemDamage > 0;
    });
  };
  _.getHousingEventForItem = function(itemId) {
    var ev, events;
    events = this.getNotUsedHousingEvents();
    ev = events.find(function(e) {
      return e.getHousingItemId() === itemId;
    });
    return ev;
  };
})();

// ■ END Game_Map.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Player.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Player.prototype;
  _.initHouseSystem = function() {
    if (this._housingEventsPlaced == null) {
      this._housingEventsPlaced = {};
      return this._extraUValue = 0;
    }
  };
  _.h_getPlacedEventIds = function() {
    var id, ids, pos, ref;
    this.initHouseSystem();
    ids = [];
    ref = this._housingEventsPlaced;
    for (id in ref) {
      pos = ref[id];
      ids.push(parseInt(id));
    }
    return ids;
  };
  _.h_getPlacedEventPositionById = function(id) {
    this.initHouseSystem();
    return this._housingEventsPlaced[id];
  };
  _.h_placeEvent = function(evId, pos) {
    this.initHouseSystem();
    if (this._housingEventsPlaced[evId] == null) {
      return this._housingEventsPlaced[evId] = pos;
    }
  };
  _.h_removeEvent = function(evId) {
    this.initHouseSystem();
    if (this._housingEventsPlaced[evId] != null) {
      return delete this._housingEventsPlaced[evId];
    }
  };
  _.h_getExtraUValue = function() {
    this.initHouseSystem();
    return this._extraUValue;
  };
  _.h_modExtraUValue = function(value) {
    this.initHouseSystem();
    return this._extraUValue += value;
  };
})();

// ■ END Game_Player.coffee
//---------------------------------------------------------------------------
//@[ALIAS]
/*ALIAS__moveByInput = _.moveByInput
_.moveByInput = ->
    if SceneManager._scene._inHousingMode is true
        return
    ALIAS__moveByInput.call(@)*/

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Map.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__onMapLoaded, _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  //@[ALIAS]
  ALIAS__onMapLoaded = _.onMapLoaded;
  _.onMapLoaded = function() {
    ALIAS__onMapLoaded.call(this);
    if ($gameMap.mapId() === $PKD_House.mapId) {
      return HouseManager.InitOnMap();
    }
  };
  //if $gameTemp._placeHouseAnimationEvent?
  //    $gameTemp._placeHouseAnimationEvent.requestAnimation($PKD_House.placeAnimtionId)
  //    $gameTemp._placeHouseAnimationEvent = null
  _.createHouseGauge = function() {
    this.shg = new Sprite_HouseGauge();
    return this.addChild(this.shg);
  };
  _.getHouseGauge = function() {
    return this.shg;
  };
  _.startHousing = function() {
    this._inHousingMode = true;
    HouseManager.HideGauge();
    return this._hh_create();
  };
})();

// ■ END Scene_Map.coffee
//---------------------------------------------------------------------------
//TODO: Переносить сцену в сцену карты!

//@[ALIAS]
/*ALIAS__terminate = _.terminate
_.terminate = ->
    if SceneManager.isNextScene(Scene_Housing)
        HouseManager.HideGauge()
        SceneManager.snapForBackgroundWithoutBlur()
    ALIAS__terminate.call(@)*/

// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ SceneManager.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = SceneManager;
  _.snapForBackgroundWithoutBlur = function() {
    return this._backgroundBitmap2 = this.snap();
  };
})();

// ■ END SceneManager.coffee
//---------------------------------------------------------------------------

// Generated by CoffeeScript 2.5.1
var Window_HousingItemsCategories;

Window_HousingItemsCategories = class Window_HousingItemsCategories extends Window_HorzCommand {
  constructor() {
    super(0, 0);
  }

  windowWidth() {
    return $PKD_House.Windows.width;
  }

  maxCols() {
    return 3;
  }

  update() {
    super.update();
    if (this._hh_itemsWindow != null) {
      return this._hh_itemsWindow.setCategory(this.currentSymbol());
    }
  }

  makeCommandList() {
    this.addCommand('All', 'all');
    this.addCommand('Coziness', 'uut');
    return this.addCommand('Decor', 'decor');
  }

  setItemWindow(_hh_itemsWindow) {
    this._hh_itemsWindow = _hh_itemsWindow;
    return this._hh_itemsWindow.setCategory('all');
  }

};

// Generated by CoffeeScript 2.5.1
var Window_Housing_ItemList;

Window_Housing_ItemList = class Window_Housing_ItemList extends Window_Selectable {
  constructor() {
    super(0, 0, $PKD_House.Windows.width, $PKD_House.Windows.height);
    this._category = 'all';
    this._data = [];
  }

  setCategory(_category) {
    if (this._category !== _category) {
      this._category = _category;
      this.refresh();
      return this.resetScroll();
    }
  }

  maxCols() {
    return 1;
  }

  spacing() {
    return 48;
  }

  isCurrentItemEnabled() {
    return true;
  }

  includes(item) {
    var value;
    if (item == null) {
      return false;
    }
    if (item.meta == null) {
      return false;
    }
    if (item.meta.houseItem == null) {
      return false;
    }
    value = parseInt(item.meta.houseItem);
    switch (this._category) {
      case 'uut':
        return value > 0;
      case 'decor':
        return value === 0;
      default:
        return true;
    }
    return false;
  }

  maxItems() {
    if (this._data != null) {
      return this._data.length;
    } else {
      return 1;
    }
  }

  needsNumber() {
    return true;
  }

  isEnabled() {
    return true;
  }

  updateHelp() {} // * EMPTY

  refresh() {
    return Window_ItemList.prototype.refresh.call(this);
  }

  makeItemList() {
    return Window_ItemList.prototype.makeItemList.call(this);
  }

  selectLast() {
    var index;
    index = this._data.indexOf($gameTemp._lastHousingItem);
    if (index >= 0) {
      return this.select(index);
    } else {
      return this.select(0);
    }
  }

  drawItem(index) {
    var item, numberWidth, rect;
    item = this._data[index];
    if (item == null) {
      return;
    }
    numberWidth = this.numberWidth();
    rect = this.itemRect(index);
    rect.width -= this.textPadding();
    this.drawItemName(item, rect.x, rect.y, rect.width - numberWidth);
    return this.drawItemNumber(item, rect.x, rect.y, rect.width);
  }

  numberWidth() {
    return this.textWidth('000');
  }

  drawItemNumber(item, x, y, width) {
    var value;
    value = parseInt(item.meta.houseItem);
    if (value > 0) {
      this.contents.textColor = KDCore.Color.FromHex($PKD_House.Windows.infoPlusTextColor).CSS;
      this.drawText('Сomfort ', x, y, width - this.textWidth('0000'), 'right');
      this.drawText("+" + value, x, y, width, 'right');
      return this.resetTextColor();
    }
  }

  item() {
    return Window_ItemList.prototype.item.call(this);
  }

};


//Plugin PKD_House automatic build by MVPluginBuilder 1.6.2 12.02.2021
